export const ROUTES = [
  '/',
  '/product',
  '/try',
  '/lab',
  '/features',
  '/features/writing-correction',
  '/features/translation',
  '/features/live-translation',
  '/features/keyboard-layout',
  '/features/speed-box',
  '/pricing',
  '/about',
  '/privacy',
  '/terms',
  '/cookies',
  '/contact',
  '/support',
  '/feedback',
  '/admin',
  '/admin/login',
  '/admin/users',
  '/admin/subscriptions',
  '/admin/usage',
  '/admin/support',
  '/admin/activity',
  '/admin/settings',
  '/admin/feedback',
  '/guide',
  '/blog',
  '/account',
  '/dashboard',
  '/dashboard/support',
  '/account/forgot-password',
  '/account/reset-password',
] as const

export type AppRoute = (typeof ROUTES)[number]
