import type { KeyboardLayout } from './types.ts'

/** Windows Russian ЙЦУКЕН on the same physical keys as US QWERTY. */
export const ruStandard: KeyboardLayout = {
  id: 'ru-standard',
  language: 'ru',
  name: 'Russian ЙЦУКЕН',
  metadata: { direction: 'ltr', hasAltGr: false, variant: 'йцукен' },
  keys: {
    Backquote: { unshifted: 'ё', shifted: 'Ё' },
    Digit1: { unshifted: '1', shifted: '!' },
    Digit2: { unshifted: '2', shifted: '"' },
    Digit3: { unshifted: '3', shifted: '№' },
    Digit4: { unshifted: '4', shifted: ';' },
    Digit5: { unshifted: '5', shifted: '%' },
    Digit6: { unshifted: '6', shifted: ':' },
    Digit7: { unshifted: '7', shifted: '?' },
    Digit8: { unshifted: '8', shifted: '*' },
    Digit9: { unshifted: '9', shifted: '(' },
    Digit0: { unshifted: '0', shifted: ')' },
    Minus: { unshifted: '-', shifted: '_' },
    Equal: { unshifted: '=', shifted: '+' },
    KeyQ: { unshifted: 'й', shifted: 'Й' },
    KeyW: { unshifted: 'ц', shifted: 'Ц' },
    KeyE: { unshifted: 'у', shifted: 'У' },
    KeyR: { unshifted: 'к', shifted: 'К' },
    KeyT: { unshifted: 'е', shifted: 'Е' },
    KeyY: { unshifted: 'н', shifted: 'Н' },
    KeyU: { unshifted: 'г', shifted: 'Г' },
    KeyI: { unshifted: 'ш', shifted: 'Ш' },
    KeyO: { unshifted: 'щ', shifted: 'Щ' },
    KeyP: { unshifted: 'з', shifted: 'З' },
    BracketLeft: { unshifted: 'х', shifted: 'Х' },
    BracketRight: { unshifted: 'ъ', shifted: 'Ъ' },
    KeyA: { unshifted: 'ф', shifted: 'Ф' },
    KeyS: { unshifted: 'ы', shifted: 'Ы' },
    KeyD: { unshifted: 'в', shifted: 'В' },
    KeyF: { unshifted: 'а', shifted: 'А' },
    KeyG: { unshifted: 'п', shifted: 'П' },
    KeyH: { unshifted: 'р', shifted: 'Р' },
    KeyJ: { unshifted: 'о', shifted: 'О' },
    KeyK: { unshifted: 'л', shifted: 'Л' },
    KeyL: { unshifted: 'д', shifted: 'Д' },
    Semicolon: { unshifted: 'ж', shifted: 'Ж' },
    Quote: { unshifted: 'э', shifted: 'Э' },
    KeyZ: { unshifted: 'я', shifted: 'Я' },
    KeyX: { unshifted: 'ч', shifted: 'Ч' },
    KeyC: { unshifted: 'с', shifted: 'С' },
    KeyV: { unshifted: 'м', shifted: 'М' },
    KeyB: { unshifted: 'и', shifted: 'И' },
    KeyN: { unshifted: 'т', shifted: 'Т' },
    KeyM: { unshifted: 'ь', shifted: 'Ь' },
    Comma: { unshifted: 'б', shifted: 'Б' },
    Period: { unshifted: 'ю', shifted: 'Ю' },
    Slash: { unshifted: '.', shifted: ',' },
  },
}
