import type { KeyboardLayout } from './types.ts'

/** Arabic 101 on the same physical keys as US QWERTY. */
export const ar101: KeyboardLayout = {
  id: 'ar-101',
  language: 'ar',
  name: 'Arabic 101',
  metadata: { direction: 'rtl', hasAltGr: false, variant: '101' },
  keys: {
    Backquote: { unshifted: 'ذ', shifted: 'ّ' },
    Digit1: { unshifted: '1', shifted: '!' },
    Digit2: { unshifted: '2', shifted: '@' },
    Digit3: { unshifted: '3', shifted: '#' },
    Digit4: { unshifted: '4', shifted: '$' },
    Digit5: { unshifted: '5', shifted: '%' },
    Digit6: { unshifted: '6', shifted: '^' },
    Digit7: { unshifted: '7', shifted: '&' },
    Digit8: { unshifted: '8', shifted: '*' },
    Digit9: { unshifted: '9', shifted: ')' },
    Digit0: { unshifted: '0', shifted: '(' },
    Minus: { unshifted: '-', shifted: '_' },
    Equal: { unshifted: '=', shifted: '+' },
    KeyQ: { unshifted: 'ض', shifted: 'َ' },
    KeyW: { unshifted: 'ص', shifted: 'ً' },
    KeyE: { unshifted: 'ث', shifted: 'ُ' },
    KeyR: { unshifted: 'ق', shifted: 'ٌ' },
    KeyT: { unshifted: 'ف', shifted: 'لإ' },
    KeyY: { unshifted: 'غ', shifted: 'إ' },
    KeyU: { unshifted: 'ع', shifted: '‘' },
    KeyI: { unshifted: 'ه', shifted: '÷' },
    KeyO: { unshifted: 'خ', shifted: '×' },
    KeyP: { unshifted: 'ح', shifted: '؛' },
    BracketLeft: { unshifted: 'ج', shifted: '<' },
    BracketRight: { unshifted: 'د', shifted: '>' },
    KeyA: { unshifted: 'ش', shifted: 'ِ' },
    KeyS: { unshifted: 'س', shifted: 'ٍ' },
    KeyD: { unshifted: 'ي', shifted: ']' },
    KeyF: { unshifted: 'ب', shifted: '[' },
    KeyG: { unshifted: 'ل', shifted: 'لأ' },
    KeyH: { unshifted: 'ا', shifted: 'أ' },
    KeyJ: { unshifted: 'ت', shifted: 'ـ' },
    KeyK: { unshifted: 'ن', shifted: '،' },
    KeyL: { unshifted: 'م', shifted: '/' },
    Semicolon: { unshifted: 'ك', shifted: ':' },
    Quote: { unshifted: 'ط', shifted: '"' },
    KeyZ: { unshifted: 'ئ', shifted: '~' },
    KeyX: { unshifted: 'ء', shifted: 'ْ' },
    KeyC: { unshifted: 'ؤ', shifted: '}' },
    KeyV: { unshifted: 'ر', shifted: '{' },
    KeyB: { unshifted: 'لا', shifted: 'لآ' },
    KeyN: { unshifted: 'ى', shifted: 'آ' },
    KeyM: { unshifted: 'ة', shifted: '’' },
    Comma: { unshifted: 'و', shifted: ',' },
    Period: { unshifted: 'ز', shifted: '.' },
    Slash: { unshifted: 'ظ', shifted: '؟' },
  },
}
