import type { KeyboardLayout } from './types.ts'

export const enUsQwerty: KeyboardLayout = {
  id: 'en-US-qwerty',
  language: 'en',
  name: 'US QWERTY',
  metadata: { direction: 'ltr', hasAltGr: false },
  keys: {
    Backquote: { unshifted: '`', shifted: '~' },
    Digit1: { unshifted: '1', shifted: '!' },
    Digit2: { unshifted: '2', shifted: '@' },
    Digit3: { unshifted: '3', shifted: '#' },
    Digit4: { unshifted: '4', shifted: '$' },
    Digit5: { unshifted: '5', shifted: '%' },
    Digit6: { unshifted: '6', shifted: '^' },
    Digit7: { unshifted: '7', shifted: '&' },
    Digit8: { unshifted: '8', shifted: '*' },
    Digit9: { unshifted: '9', shifted: '(' },
    Digit0: { unshifted: '0', shifted: ')' },
    Minus: { unshifted: '-', shifted: '_' },
    Equal: { unshifted: '=', shifted: '+' },
    KeyQ: { unshifted: 'q', shifted: 'Q' },
    KeyW: { unshifted: 'w', shifted: 'W' },
    KeyE: { unshifted: 'e', shifted: 'E' },
    KeyR: { unshifted: 'r', shifted: 'R' },
    KeyT: { unshifted: 't', shifted: 'T' },
    KeyY: { unshifted: 'y', shifted: 'Y' },
    KeyU: { unshifted: 'u', shifted: 'U' },
    KeyI: { unshifted: 'i', shifted: 'I' },
    KeyO: { unshifted: 'o', shifted: 'O' },
    KeyP: { unshifted: 'p', shifted: 'P' },
    BracketLeft: { unshifted: '[', shifted: '{' },
    BracketRight: { unshifted: ']', shifted: '}' },
    KeyA: { unshifted: 'a', shifted: 'A' },
    KeyS: { unshifted: 's', shifted: 'S' },
    KeyD: { unshifted: 'd', shifted: 'D' },
    KeyF: { unshifted: 'f', shifted: 'F' },
    KeyG: { unshifted: 'g', shifted: 'G' },
    KeyH: { unshifted: 'h', shifted: 'H' },
    KeyJ: { unshifted: 'j', shifted: 'J' },
    KeyK: { unshifted: 'k', shifted: 'K' },
    KeyL: { unshifted: 'l', shifted: 'L' },
    Semicolon: { unshifted: ';', shifted: ':' },
    Quote: { unshifted: "'", shifted: '"' },
    KeyZ: { unshifted: 'z', shifted: 'Z' },
    KeyX: { unshifted: 'x', shifted: 'X' },
    KeyC: { unshifted: 'c', shifted: 'C' },
    KeyV: { unshifted: 'v', shifted: 'V' },
    KeyB: { unshifted: 'b', shifted: 'B' },
    KeyN: { unshifted: 'n', shifted: 'N' },
    KeyM: { unshifted: 'm', shifted: 'M' },
    Comma: { unshifted: ',', shifted: '<' },
    Period: { unshifted: '.', shifted: '>' },
    Slash: { unshifted: '/', shifted: '?' },
  },
}
