import { enUsQwerty } from './en-US-qwerty.ts'
import type { KeyboardLayout, KeyOutput, PhysicalKeyId } from './types.ts'

function extend(
  layout: Omit<KeyboardLayout, 'keys'> & {
    keys: Partial<Record<PhysicalKeyId, KeyOutput>>
  },
): KeyboardLayout {
  return {
    ...layout,
    keys: { ...enUsQwerty.keys, ...layout.keys },
  }
}

/** German QWERTZ (Windows). */
export const deQwertz: KeyboardLayout = extend({
  id: 'de-qwertz',
  language: 'de',
  name: 'German QWERTZ',
  metadata: { direction: 'ltr', hasAltGr: true, variant: 'qwertz' },
  keys: {
    Backquote: { unshifted: '^', shifted: '°' },
    Digit2: { unshifted: '2', shifted: '"', altGr: '²' },
    Digit3: { unshifted: '3', shifted: '§', altGr: '³' },
    Digit6: { unshifted: '6', shifted: '&' },
    Digit7: { unshifted: '7', shifted: '/', altGr: '{' },
    Digit8: { unshifted: '8', shifted: '(', altGr: '[' },
    Digit9: { unshifted: '9', shifted: ')', altGr: ']' },
    Digit0: { unshifted: '0', shifted: '=', altGr: '}' },
    Minus: { unshifted: 'ß', shifted: '?', altGr: '\\' },
    Equal: { unshifted: '´', shifted: '`' },
    KeyY: { unshifted: 'z', shifted: 'Z' },
    KeyZ: { unshifted: 'y', shifted: 'Y' },
    BracketLeft: { unshifted: 'ü', shifted: 'Ü' },
    BracketRight: { unshifted: '+', shifted: '*', altGr: '~' },
    Semicolon: { unshifted: 'ö', shifted: 'Ö' },
    Quote: { unshifted: 'ä', shifted: 'Ä' },
    Comma: { unshifted: ',', shifted: ';' },
    Period: { unshifted: '.', shifted: ':' },
    Slash: { unshifted: '-', shifted: '_' },
  },
})

/** French AZERTY (Windows France). */
export const frAzerty: KeyboardLayout = extend({
  id: 'fr-azerty',
  language: 'fr',
  name: 'French AZERTY',
  metadata: { direction: 'ltr', hasAltGr: true, variant: 'azerty' },
  keys: {
    Backquote: { unshifted: '²', shifted: '²' },
    Digit1: { unshifted: '&', shifted: '1' },
    Digit2: { unshifted: 'é', shifted: '2', altGr: '~' },
    Digit3: { unshifted: '"', shifted: '3', altGr: '#' },
    Digit4: { unshifted: "'", shifted: '4', altGr: '{' },
    Digit5: { unshifted: '(', shifted: '5', altGr: '[' },
    Digit6: { unshifted: '-', shifted: '6', altGr: '|' },
    Digit7: { unshifted: 'è', shifted: '7' },
    Digit8: { unshifted: '_', shifted: '8', altGr: '\\' },
    Digit9: { unshifted: 'ç', shifted: '9', altGr: '^' },
    Digit0: { unshifted: 'à', shifted: '0', altGr: '@' },
    Minus: { unshifted: ')', shifted: '°', altGr: ']' },
    Equal: { unshifted: '=', shifted: '+', altGr: '}' },
    KeyQ: { unshifted: 'a', shifted: 'A' },
    KeyW: { unshifted: 'z', shifted: 'Z' },
    KeyA: { unshifted: 'q', shifted: 'Q' },
    KeyZ: { unshifted: 'w', shifted: 'W' },
    BracketLeft: { unshifted: '^', shifted: '¨' },
    BracketRight: { unshifted: '$', shifted: '£', altGr: '¤' },
    Semicolon: { unshifted: 'm', shifted: 'M' },
    Quote: { unshifted: 'ù', shifted: '%' },
    KeyM: { unshifted: ',', shifted: '?' },
    Comma: { unshifted: ';', shifted: '.' },
    Period: { unshifted: ':', shifted: '/' },
    Slash: { unshifted: '!', shifted: '§' },
  },
})

/** Turkish Q (Windows). */
export const trQ: KeyboardLayout = extend({
  id: 'tr-q',
  language: 'tr',
  name: 'Turkish Q',
  metadata: { direction: 'ltr', hasAltGr: true, variant: 'q' },
  keys: {
    Backquote: { unshifted: '"', shifted: 'é', altGr: '<' },
    Digit1: { unshifted: '1', shifted: '!', altGr: '>' },
    Digit2: { unshifted: '2', shifted: "'", altGr: '£' },
    Digit3: { unshifted: '3', shifted: '^', altGr: '#' },
    Digit4: { unshifted: '4', shifted: '+', altGr: '$' },
    Digit5: { unshifted: '5', shifted: '%', altGr: '½' },
    Digit6: { unshifted: '6', shifted: '&' },
    Digit7: { unshifted: '7', shifted: '/', altGr: '{' },
    Digit8: { unshifted: '8', shifted: '(', altGr: '[' },
    Digit9: { unshifted: '9', shifted: ')', altGr: ']' },
    Digit0: { unshifted: '0', shifted: '=', altGr: '}' },
    Minus: { unshifted: '*', shifted: '?', altGr: '\\' },
    Equal: { unshifted: '-', shifted: '_' },
    KeyI: { unshifted: 'ı', shifted: 'I' },
    BracketLeft: { unshifted: 'ğ', shifted: 'Ğ', altGr: '¨' },
    BracketRight: { unshifted: 'ü', shifted: 'Ü', altGr: '~' },
    Semicolon: { unshifted: 'ş', shifted: 'Ş', altGr: '´' },
    Quote: { unshifted: 'i', shifted: 'İ' },
    Comma: { unshifted: 'ö', shifted: 'Ö' },
    Period: { unshifted: 'ç', shifted: 'Ç' },
    Slash: { unshifted: '.', shifted: ':' },
  },
})

/** Hebrew (Windows). Unshifted is Hebrew; Shift is Latin. */
export const heStandard: KeyboardLayout = extend({
  id: 'he-standard',
  language: 'he',
  name: 'Hebrew',
  metadata: { direction: 'rtl', hasAltGr: false, variant: 'standard' },
  keys: {
    KeyQ: { unshifted: '/', shifted: 'Q' },
    KeyW: { unshifted: "'", shifted: 'W' },
    KeyE: { unshifted: 'ק', shifted: 'E' },
    KeyR: { unshifted: 'ר', shifted: 'R' },
    KeyT: { unshifted: 'א', shifted: 'T' },
    KeyY: { unshifted: 'ט', shifted: 'Y' },
    KeyU: { unshifted: 'ו', shifted: 'U' },
    KeyI: { unshifted: 'ן', shifted: 'I' },
    KeyO: { unshifted: 'ם', shifted: 'O' },
    KeyP: { unshifted: 'פ', shifted: 'P' },
    BracketLeft: { unshifted: ']', shifted: '}' },
    BracketRight: { unshifted: '[', shifted: '{' },
    KeyA: { unshifted: 'ש', shifted: 'A' },
    KeyS: { unshifted: 'ד', shifted: 'S' },
    KeyD: { unshifted: 'ג', shifted: 'D' },
    KeyF: { unshifted: 'כ', shifted: 'F' },
    KeyG: { unshifted: 'ע', shifted: 'G' },
    KeyH: { unshifted: 'י', shifted: 'H' },
    KeyJ: { unshifted: 'ח', shifted: 'J' },
    KeyK: { unshifted: 'ל', shifted: 'K' },
    KeyL: { unshifted: 'ך', shifted: 'L' },
    Semicolon: { unshifted: 'ף', shifted: ':' },
    Quote: { unshifted: ',', shifted: '"' },
    KeyZ: { unshifted: 'ז', shifted: 'Z' },
    KeyX: { unshifted: 'ס', shifted: 'X' },
    KeyC: { unshifted: 'ב', shifted: 'C' },
    KeyV: { unshifted: 'ה', shifted: 'V' },
    KeyB: { unshifted: 'נ', shifted: 'B' },
    KeyN: { unshifted: 'מ', shifted: 'N' },
    KeyM: { unshifted: 'צ', shifted: 'M' },
    Comma: { unshifted: 'ת', shifted: '>' },
    Period: { unshifted: 'ץ', shifted: '<' },
    Slash: { unshifted: '.', shifted: '?' },
  },
})

/** Greek (Windows). */
export const elStandard: KeyboardLayout = extend({
  id: 'el-standard',
  language: 'el',
  name: 'Greek',
  metadata: { direction: 'ltr', hasAltGr: false, variant: 'standard' },
  keys: {
    KeyQ: { unshifted: ';', shifted: ':' },
    KeyW: { unshifted: 'ς', shifted: '΅' },
    KeyE: { unshifted: 'ε', shifted: 'Ε' },
    KeyR: { unshifted: 'ρ', shifted: 'Ρ' },
    KeyT: { unshifted: 'τ', shifted: 'Τ' },
    KeyY: { unshifted: 'υ', shifted: 'Υ' },
    KeyU: { unshifted: 'θ', shifted: 'Θ' },
    KeyI: { unshifted: 'ι', shifted: 'Ι' },
    KeyO: { unshifted: 'ο', shifted: 'Ο' },
    KeyP: { unshifted: 'π', shifted: 'Π' },
    KeyA: { unshifted: 'α', shifted: 'Α' },
    KeyS: { unshifted: 'σ', shifted: 'Σ' },
    KeyD: { unshifted: 'δ', shifted: 'Δ' },
    KeyF: { unshifted: 'φ', shifted: 'Φ' },
    KeyG: { unshifted: 'γ', shifted: 'Γ' },
    KeyH: { unshifted: 'η', shifted: 'Η' },
    KeyJ: { unshifted: 'ξ', shifted: 'Ξ' },
    KeyK: { unshifted: 'κ', shifted: 'Κ' },
    KeyL: { unshifted: 'λ', shifted: 'Λ' },
    KeyZ: { unshifted: 'ζ', shifted: 'Ζ' },
    KeyX: { unshifted: 'χ', shifted: 'Χ' },
    KeyC: { unshifted: 'ψ', shifted: 'Ψ' },
    KeyV: { unshifted: 'ω', shifted: 'Ω' },
    KeyB: { unshifted: 'β', shifted: 'Β' },
    KeyN: { unshifted: 'ν', shifted: 'Ν' },
    KeyM: { unshifted: 'μ', shifted: 'Μ' },
  },
})

/** Spanish Latin American (Windows). */
export const esLatam: KeyboardLayout = extend({
  id: 'es-latam',
  language: 'es',
  name: 'Spanish Latin American',
  metadata: { direction: 'ltr', hasAltGr: true, variant: 'latam' },
  keys: {
    Minus: { unshifted: "'", shifted: '?' },
    Equal: { unshifted: '¿', shifted: '¡' },
    BracketLeft: { unshifted: '´', shifted: '¨' },
    BracketRight: { unshifted: '+', shifted: '*', altGr: '~' },
    Semicolon: { unshifted: 'ñ', shifted: 'Ñ' },
    Quote: { unshifted: '{', shifted: '[', altGr: '^' },
  },
})

/** Italian (Windows). */
export const itStandard: KeyboardLayout = extend({
  id: 'it-standard',
  language: 'it',
  name: 'Italian',
  metadata: { direction: 'ltr', hasAltGr: true, variant: 'standard' },
  keys: {
    Minus: { unshifted: "'", shifted: '?' },
    Equal: { unshifted: 'ì', shifted: '^' },
    BracketLeft: { unshifted: 'è', shifted: 'é', altGr: '[' },
    BracketRight: { unshifted: '+', shifted: '*', altGr: ']' },
    Semicolon: { unshifted: 'ò', shifted: 'ç', altGr: '@' },
    Quote: { unshifted: 'à', shifted: '°', altGr: '#' },
  },
})

/** Brazilian Portuguese letter row on a 101-key frame (ç on Semicolon). */
export const ptAbnt: KeyboardLayout = extend({
  id: 'pt-abnt',
  language: 'pt',
  name: 'Portuguese Brazil',
  metadata: { direction: 'ltr', hasAltGr: true, variant: 'abnt-101' },
  keys: {
    Semicolon: { unshifted: 'ç', shifted: 'Ç' },
    Quote: { unshifted: '~', shifted: '^' },
  },
})

/** Ukrainian ЙЦУКЕН (Windows). */
export const ukStandard: KeyboardLayout = {
  id: 'uk-standard',
  language: 'uk',
  name: 'Ukrainian',
  metadata: { direction: 'ltr', hasAltGr: false, variant: 'йцукен' },
  keys: {
    Backquote: { unshifted: 'ё', shifted: 'Ё' },
    Digit1: { unshifted: '1', shifted: '!' },
    Digit2: { unshifted: '2', shifted: '"' },
    Digit3: { unshifted: '3', shifted: '№' },
    Digit4: { unshifted: '4', shifted: ';' },
    Digit5: { unshifted: '5', shifted: '%' },
    Digit6: { unshifted: '6', shifted: ':' },
    Digit7: { unshifted: '7', shifted: '?' },
    Digit8: { unshifted: '8', shifted: '*' },
    Digit9: { unshifted: '9', shifted: '(' },
    Digit0: { unshifted: '0', shifted: ')' },
    Minus: { unshifted: '-', shifted: '_' },
    Equal: { unshifted: '=', shifted: '+' },
    KeyQ: { unshifted: 'й', shifted: 'Й' },
    KeyW: { unshifted: 'ц', shifted: 'Ц' },
    KeyE: { unshifted: 'у', shifted: 'У' },
    KeyR: { unshifted: 'к', shifted: 'К' },
    KeyT: { unshifted: 'е', shifted: 'Е' },
    KeyY: { unshifted: 'н', shifted: 'Н' },
    KeyU: { unshifted: 'г', shifted: 'Г' },
    KeyI: { unshifted: 'ш', shifted: 'Ш' },
    KeyO: { unshifted: 'щ', shifted: 'Щ' },
    KeyP: { unshifted: 'з', shifted: 'З' },
    BracketLeft: { unshifted: 'х', shifted: 'Х' },
    BracketRight: { unshifted: 'ї', shifted: 'Ї' },
    KeyA: { unshifted: 'ф', shifted: 'Ф' },
    KeyS: { unshifted: 'і', shifted: 'І' },
    KeyD: { unshifted: 'в', shifted: 'В' },
    KeyF: { unshifted: 'а', shifted: 'А' },
    KeyG: { unshifted: 'п', shifted: 'П' },
    KeyH: { unshifted: 'р', shifted: 'Р' },
    KeyJ: { unshifted: 'о', shifted: 'О' },
    KeyK: { unshifted: 'л', shifted: 'Л' },
    KeyL: { unshifted: 'д', shifted: 'Д' },
    Semicolon: { unshifted: 'ж', shifted: 'Ж' },
    Quote: { unshifted: 'є', shifted: 'Є' },
    KeyZ: { unshifted: 'я', shifted: 'Я' },
    KeyX: { unshifted: 'ч', shifted: 'Ч' },
    KeyC: { unshifted: 'с', shifted: 'С' },
    KeyV: { unshifted: 'м', shifted: 'М' },
    KeyB: { unshifted: 'и', shifted: 'И' },
    KeyN: { unshifted: 'т', shifted: 'Т' },
    KeyM: { unshifted: 'ь', shifted: 'Ь' },
    Comma: { unshifted: 'б', shifted: 'Б' },
    Period: { unshifted: 'ю', shifted: 'Ю' },
    Slash: { unshifted: '.', shifted: ',' },
  },
}

/** Persian (Windows Iranian). */
export const faStandard: KeyboardLayout = {
  id: 'fa-standard',
  language: 'fa',
  name: 'Persian',
  metadata: { direction: 'rtl', hasAltGr: false, variant: 'standard' },
  keys: {
    Backquote: { unshifted: 'پ', shifted: '÷' },
    Digit1: { unshifted: '۱', shifted: '!' },
    Digit2: { unshifted: '۲', shifted: '@' },
    Digit3: { unshifted: '۳', shifted: '#' },
    Digit4: { unshifted: '۴', shifted: '$' },
    Digit5: { unshifted: '۵', shifted: '%' },
    Digit6: { unshifted: '۶', shifted: '^' },
    Digit7: { unshifted: '۷', shifted: '&' },
    Digit8: { unshifted: '۸', shifted: '*' },
    Digit9: { unshifted: '۹', shifted: ')' },
    Digit0: { unshifted: '۰', shifted: '(' },
    Minus: { unshifted: '-', shifted: '_' },
    Equal: { unshifted: '=', shifted: '+' },
    KeyQ: { unshifted: 'ض', shifted: 'ْ' },
    KeyW: { unshifted: 'ص', shifted: 'ٌ' },
    KeyE: { unshifted: 'ث', shifted: 'ٍ' },
    KeyR: { unshifted: 'ق', shifted: 'ً' },
    KeyT: { unshifted: 'ف', shifted: 'ُ' },
    KeyY: { unshifted: 'غ', shifted: 'ِ' },
    KeyU: { unshifted: 'ع', shifted: 'َ' },
    KeyI: { unshifted: 'ه', shifted: 'ّ' },
    KeyO: { unshifted: 'خ', shifted: ']' },
    KeyP: { unshifted: 'ح', shifted: '[' },
    BracketLeft: { unshifted: 'ج', shifted: '}' },
    BracketRight: { unshifted: 'چ', shifted: '{' },
    KeyA: { unshifted: 'ش', shifted: 'ؤ' },
    KeyS: { unshifted: 'س', shifted: 'ئ' },
    KeyD: { unshifted: 'ی', shifted: 'ي' },
    KeyF: { unshifted: 'ب', shifted: 'إ' },
    KeyG: { unshifted: 'ل', shifted: 'أ' },
    KeyH: { unshifted: 'ا', shifted: 'آ' },
    KeyJ: { unshifted: 'ت', shifted: 'ة' },
    KeyK: { unshifted: 'ن', shifted: '»' },
    KeyL: { unshifted: 'م', shifted: '«' },
    Semicolon: { unshifted: 'ک', shifted: ':' },
    Quote: { unshifted: 'گ', shifted: '"' },
    KeyZ: { unshifted: 'ظ', shifted: 'ك' },
    KeyX: { unshifted: 'ط', shifted: 'ٓ' },
    KeyC: { unshifted: 'ز', shifted: 'ژ' },
    KeyV: { unshifted: 'ر', shifted: 'ٰ' },
    KeyB: { unshifted: 'ذ', shifted: '\u200c' },
    KeyN: { unshifted: 'د', shifted: '\u200d' },
    KeyM: { unshifted: 'پ', shifted: 'ء' },
    Comma: { unshifted: 'و', shifted: '<' },
    Period: { unshifted: '.', shifted: '>' },
    Slash: { unshifted: '/', shifted: '؟' },
  },
}

export const WORLD_LAYOUTS: KeyboardLayout[] = [
  deQwertz,
  frAzerty,
  trQ,
  heStandard,
  elStandard,
  esLatam,
  itStandard,
  ptAbnt,
  ukStandard,
  faStandard,
]
